<?php
// We set the page title first, as it's needed by the header.
$page_title = "Manage Assets";

// We must include session_check and permissions first to know who the user is.
// The header.php file already includes these, so we can just include it first,
// but we will move the permission check before any HTML is generated by the header.
// Let's correct the order entirely for clarity.

include('../../includes/session_check.php'); // Ensures user is logged in
include('../../includes/permissions.php'); // Makes has_permission() available

// --- THIS IS THE CORRECTED LOGIC ---
// STEP 1: Check for permission BEFORE any HTML is printed.
if (!has_permission('asset_view') && !has_permission('asset_manage')) {
    // If permission is denied, send the header redirect and stop the script.
    header('Location: /erp_project/index.php?status=access_denied');
    exit();
}

// STEP 2: If permission check passes, THEN include the header to draw the page.
include('../../includes/header.php');
include('../../includes/db.php');
$conn = connect_db();

// The rest of the page logic remains the same.
$sql = "SELECT 
            a.*, 
            at.type_name,
            CONCAT(e.first_name, ' ', e.last_name) as assigned_to_name
        FROM assets a
        JOIN asset_types at ON a.asset_type_id = at.id
        LEFT JOIN employees e ON a.assigned_to_employee_id = e.id
        ORDER BY a.asset_name ASC";
$result = $conn->query($sql);
$can_manage = has_permission('asset_manage');
?>

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/erp_project/index.php">Home</a></li>
    <li class="breadcrumb-item">Inventory</li>
    <li class="breadcrumb-item active" aria-current="page">Manage Assets</li>
  </ol>
</nav>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1><?php echo $page_title; ?></h1>
    <?php if ($can_manage): ?>
        <a href="add_asset.php" class="btn btn-primary"><i class="bi bi-plus-circle me-2"></i>Add New Asset</a>
    <?php endif; ?>
</div>

<div class="card">
    <div class="card-header"><h5>All Company Assets</h5></div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead><tr><th>Asset Name</th><th>Asset Tag</th><th>Type</th><th>Assigned To</th><th>Status</th><?php if ($can_manage): ?><th>Actions</th><?php endif; ?></tr></thead>
                <tbody>
                    <?php if ($result && $result->num_rows > 0): ?>
                        <?php while($row = $result->fetch_assoc()): ?>
                            <tr>
                                <td><?php echo htmlspecialchars($row['asset_name']); ?></td>
                                <td><?php echo htmlspecialchars($row['asset_tag']); ?></td>
                                <td><?php echo htmlspecialchars($row['type_name']); ?></td>
                                <td><?php echo $row['assigned_to_name'] ? htmlspecialchars($row['assigned_to_name']) : '<span class="text-muted">In Stock</span>'; ?></td>
                                <td><?php echo htmlspecialchars($row['status']); ?></td>
                                <?php if ($can_manage): ?>
                                <td>
                                    <a href="edit_asset.php?id=<?php echo $row['id']; ?>" class="btn btn-sm btn-warning"><i class="bi bi-pencil-square"></i></a>
                                    <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteAssetModal" data-id="<?php echo $row['id']; ?>"><i class="bi bi-trash"></i></button>
                                </td>
                                <?php endif; ?>
                            </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr><td colspan="<?php echo $can_manage ? '6' : '5'; ?>" class="text-center text-muted">No assets found.</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="deleteAssetModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header"><h5 class="modal-title">Confirm Deletion</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
      <div class="modal-body">Are you sure you want to delete this asset record? <p class="text-danger small">This action cannot be undone.</p></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form action="handle_delete_asset.php" method="POST" class="d-inline">
            <input type="hidden" name="id" id="delete_asset_id">
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

<?php
$conn->close();
include('../../includes/footer.php');
?>